name: PRs trigger PR_target

# This workflow runs when a PR is opened targeting 'main'
on:
  pull_request_target:
    types: [opened]
    branches: [ main ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    # Give the job write permissions to add labels
    permissions:
      pull-requests: write
      
    steps:
      # - name: Add 'needs-review' label
      #   # This action needs a GITHUB_TOKEN with write access
      #   # 'pull_request_target' provides it.
      #   uses: actions/labeler@v5
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sleeping job 1 for 5 minutes
        run: |
          echo "Job 1 starting sleep for 300 seconds"
          sleep 5
          echo "Job 1 finished sleeping"

      - name: Checkout code
        with:
            ref: ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v5 
          
      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci.sh
          ./run_fibonacci.sh
